platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/Devinet_Team/ios-pod-repo.git'

target 'DVNTStoreKitManager_Example' do
  pod 'DVNTStoreKitManager', :path => '../'
end
